// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHqVoRWYiC2NKlRi6cTpAqWBq7trj-hw',
    appId: '1:181071333515:web:b6aac4de3ecb91471cac8e',
    messagingSenderId: '181071333515',
    projectId: 'tad-id',
    authDomain: 'tad-id.firebaseapp.com',
    storageBucket: 'tad-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZChiXzfgZWzYLZ1E6_3iIzcnDvqAV3fA',
    appId: '1:181071333515:android:2ecb2df6fecc05661cac8e',
    messagingSenderId: '181071333515',
    projectId: 'tad-id',
    storageBucket: 'tad-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSdgrfVvMtHdFKlBhE4dSc6bxUpNmYnU',
    appId: '1:181071333515:ios:305f59d8c6a71b471cac8e',
    messagingSenderId: '181071333515',
    projectId: 'tad-id',
    storageBucket: 'tad-id.firebasestorage.app',
    iosBundleId: 'com.example.eas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSdgrfVvMtHdFKlBhE4dSc6bxUpNmYnU',
    appId: '1:181071333515:ios:305f59d8c6a71b471cac8e',
    messagingSenderId: '181071333515',
    projectId: 'tad-id',
    storageBucket: 'tad-id.firebasestorage.app',
    iosBundleId: 'com.example.eas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByHqVoRWYiC2NKlRi6cTpAqWBq7trj-hw',
    appId: '1:181071333515:web:abf722f3ef02e59e1cac8e',
    messagingSenderId: '181071333515',
    projectId: 'tad-id',
    authDomain: 'tad-id.firebaseapp.com',
    storageBucket: 'tad-id.firebasestorage.app',
  );
}
